config/routes.rb
FallenLeaf::Application.routes.draw do
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'

  resources :projects,    only: [:index, :show]
  resources :collections, only: [:index, :show]
  resources :images,      only: [:index, :show], path: 'gallery'

  namespace :admin do
    resources :images
    resources :projects
  end

  root 'pages#index'
end

app/models/image.rb
class Image < ActiveRecord::Base

  has_attached_file :source, styles: {
    square: '250x250#',
    full: "700x700"
  }

  validates_attachment_content_type :source, :content_type => /\Aimage\/.*\Z/

end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    prepend_before_action :authenticate_admin!
    layout 'admin'

  private

    def authenticate_admin!
      authenticate_or_request_with_http_basic do |username, password|
        username == "admin" && password == "leaf kill will stream"
      end
    end

  end
end

app/controllers/admin/images_controller.rb
module Admin
  class ImagesController < BaseController
    inherit_resources

  private

    def permitted_params
      params.permit image: [:name, :source]
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

  def index
  end

  def show
    redirect_to collections_path
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @images = Image.limit(25).order('created_at DESC')
  end

  def show
    @image = Image.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def about
  end

  def contact
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
  end

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def time_tag_for(object)
    time_tag object.updated_at,
             object.updated_at.to_s(:long),
             class: "data-item__time"
  end

  def yes_no(a)
    a ? "Yes" : "No"
  end

  def admin_nav_actions_for(o)
    links = "".html_safe

    links <<  link_to('Show', polymorphic_path([:admin, o]), class: "action")
    links <<  link_to('Delete', polymorphic_path([:admin, o]),
                      method: :delete,  class: "action",
                      confirm: "Are you sure?")

    content_tag :nav, links, class: "data-item__actions"
  end

end

app/views/admin/images/_form.html.erb
<%= form_for [:admin, resource] do |f| %>

  <div class="form__fields form__fields--primary">

    <div class="form__field form__field--no-label">
      <%= f.label :name %>
      <%= f.text_field :name, placeholder: "Name your image"  %>
    </div>

    <div class="form__field">
      <%= f.file_field :source %>
      <p class="form__field-note">
        Your image should be 1200 x 300. This will appear inside the header.
      </p>
    </div>

    <div class="form__field form__field--actions">
      <%= f.submit resource.persisted? ? "Update" : "Publish",
                   { class: "button button--primary" } %>
    </div>

  </div>

<% end %>

app/views/admin/images/_image.html.erb
<tr class="data-item">
  <td><%= image.id %></td>
  <td><%= image.name %></td>
  <td><%= admin_nav_actions_for(image) %></td>
  <td><%= time_tag_for(image) %></td>
</tr>

app/views/admin/images/edit.html.erb
<header class="page-header">
  <h1 class="page-header__title">Editing <%= resource.name %></h1>

  <%= link_to 'All images', admin_images_path,
                 class: "button button--secondary page-header__cta" %>
</header>

<%= render "form" %>

app/views/admin/images/index.html.erb
<header class="page-header">
  <h1 class="page-header__title">Images</h1>

  <%= link_to 'New Image', new_admin_image_path,
               class: "button button--primary page-header__cta" %>
</header>

<%= render "data_table", columns: ["ID", "Name", "Actions", "Updated"] %>

app/views/admin/images/new.html.erb
<header class="page-header">
  <h1 class="page-header__title">Images</h1>

  <%= link_to 'All images', admin_images_path,
               class: "button button--secondary page-header__cta" %>
</header>

<%= render "form" %>

app/views/admin/images/show.html.erb
<header class="page-header">
  <h1 class="page-header__title"><%= resource.name %></h1>

  <%= link_to 'All images', admin_images_path,
               class: "button button--secondary page-header__cta" %>

  <%= link_to 'Edit', edit_admin_image_path(resource),
               class: "button button--primary page-header__cta" %>
</header>

<%= image_tag resource.source.url(:full) %>

app/views/application/_data_table.html.erb
<table class="data-items">
  <thead>
    <tr>
      <% columns.each do |c| %>
        <th><%= c %></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <%= render collection %>
  </tbody>

</table>

app/views/collections/index.html.erb
<section class="page-content page-content--contact">
  <h2>Collections</h2>

  <p>We'll soon be launching a range of products you can purchase. In the meantime, if you'd like to view some of our previous work take a look at the gallery.</p>
</section>

app/views/images/index.html.erb
<div class="gallery">
  <ul class="gallery__items">
    <% @images.each do |image| %>
      <li class="gallery__item">
        <a href="<%= image_path(image) %>">
          <img data-full="<%= image.source.url(:full) %>"
              src="<%= image.source.url(:square) %>" class="gallery__item__img">
        </a>
      </li>
    <% end %>
  </ul>
</div>

app/views/images/show.html.erb
<div class="gallery-cover"></div>
<section class="gallery-item">
  <img src="<%= @image.source.url(:full) %>" class="gallery-item__img">

  <%= link_to "Back to all images", images_path, class: 'gallery-item__nav-link' %>
</section>

app/views/layouts/_footer.html.erb
<footer class="site-footer">
  <nav class="site-footer__items">
    <ul class="social-icons__items">
      <!-- <li class="social-icons__item">
        <a href="https://www.facebook.com/beynonstudio" class="social-icons__item__link social-icons__item__link--facebook">
          <span class="social-icons__item__text">
            Facebook
          </span>
        </a>
      </li> -->
      <li class="social-icons__item">
        <a href="https://twitter.com/cf_fallenleaf" class="social-icons__item__link social-icons__item__link--twitter">
          <span class="social-icons__item__text">
            Twitter
          </span>
        </a>
      </li>
      <li class="social-icons__item">
        <a href="http://instagram.com/fallenleaffurniture" class="social-icons__item__link social-icons__item__link--instagram">
          <span class="social-icons__item__text">
            Instagram
          </span>
        </a>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="site-header">
  <%= link_to root_path, class: "site-header__logo" do %>
    <span class="site-header__logo__script">
      Fallen Leaf Furniture
    </span>
  <% end %>

  <%= render "layouts/navigation" %>
</header>

app/views/layouts/_navigation.html.erb
<nav class="site-nav js-site-nav">
  <a href="#" class="site-nav__hamburger js-menu-toggle">&#9776;</a>

  <ul class="site-nav__items is-hidden js-nav-items">
    <li class="site-nav__item">
      <%= link_to "About", about_path, class: "site-nav__link" %>
    </li>
    <li class="site-nav__item">
      <%= link_to "Gallery", images_path, class: "site-nav__link" %>
    </li>
    <li class="site-nav__item">
      <%= link_to "Collection", collections_path, class: "site-nav__link" %>
    </li>
    <!-- <li class="site-nav__item">
      <%= link_to "Projects", projects_path, class: "site-nav__link" %>
    </li> -->
    <li class="site-nav__item site-nav__item--last">
      <%= link_to "Contact", contact_path, class: "site-nav__link" %>
    </li>
  </ul>
</nav>

app/views/layouts/admin.html.erb
<html class="no-js">
  <head>
    <title>Fallen Leaf Furniture | Admin</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Gilda+Display' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "admin" %>
  </head>
  <body class="site site--<%= controller_name %>" data-module="<%= controller_name %>" data-action="<%= action_name %>">


    <%#= render "flash_messages" %>
    <%= render 'layouts/admin/header' %>

    <div class="site-content container">
      <%= yield %>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/admin/_header.html.erb
<header class="site-header">
  <div class="container">

    <a href="/admin/images" class="site-logo">
      Fallen Leaf Furniture
    </a>

    <%= render "layouts/admin/navigation" %>

  </div>
</header>

app/views/layouts/admin/_navigation.html.erb
<nav class="site-nav">
  <ul class="site-nav__items">

    <li class="site-nav__item">
      <%= link_to "Images", admin_images_path %>
    </li>

  </ul>
</nav>

app/views/layouts/application.html.erb
<html class="no-js">
  <head>
    <title>Fallen Leaf Furniture | Bespoke handmade furniture in England</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Bespoke, handmade furniture by Christopher French in England.">
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Gilda+Display' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "application" %>
  </head>
  <body class="site site--<%= controller_name %>"
        data-module="<%= controller_name %>" data-action="<%= action_name %>">
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <%= javascript_include_tag "application" %>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-42942204-1', 'fallenleaf.co');
      ga('send', 'pageview');

    </script>
  </body>
</html>

app/views/pages/about.html.erb
<section class="page-content page-content--about">

  <p>Fallen Leaf furniture was created to produce bespoke handmade furniture using traditional techniques and beautiful quality timbers. The aim is to craft pieces that are aesthetically stunning, sculpturally complex and that pay homage to the material used.</p>

  <p>Using exquisite timbers from sustainable sources and nearly a decade of woodworking experience, Fallen Leaf furniture aspires to change the perceptions of furniture and the relationship we have with it.</p>

</section>

app/views/pages/contact.html.erb
<section class="page-content page-content--contact">
  <h2>Contact</h2>

  <p>
    +44 (0) 7986 154 441 <br>
    <a href="mailto:commissions@fallenleaf.co">commisions@fallenleaf.co</a>
  </p>

  <p>
    Instagram: <a href="http://instagram.com/fallenleaffurniture">@fallenleaffurniture</a><br>
    Twitter: <a href="http://twitter.com/cf_fallenleaf">@cf_fallenleaf</a>
  </p>
</section>